import os
from typing import Dict, Any
from backend.integrations.netsuite.client import LiveNetSuiteClient, MockNetSuiteClient
from backend.integrations.netsuite.schemas import NetSuiteSyncResponse, NetSuiteStatus

class NetSuiteAdapter:
    """
    Acts as the architectural boundary between ProcuraIQ core and the NetSuite API.
    Provides standard procurement data mapping and synchronization.
    """
    def __init__(self):
        use_mock = os.getenv("NETSUITE_USE_MOCK", "false").lower() == "true"
        
        # Instantiate both clients
        self.live_client = LiveNetSuiteClient()
        self.mock_client = MockNetSuiteClient()
        
        # Decide which client to use based on configuration
        if use_mock:
            self.client = self.mock_client
            self.mode = "DEVELOPMENT/MOCK"
        elif self.live_client.is_available():
            self.client = self.live_client
            self.mode = "LIVE"
        else:
            self.client = None
            self.mode = "CONFIGURATION REQUIRED"

    def get_status(self) -> NetSuiteStatus:
        if self.mode == "LIVE":
            return NetSuiteStatus(status="CONNECTED", message="Live NetSuite connection established.", mode=self.mode)
        elif self.mode == "DEVELOPMENT/MOCK":
            return NetSuiteStatus(status="CONNECTED", message="Demo mode active. Data is mocked.", mode=self.mode)
        else:
            return NetSuiteStatus(status="NOT CONNECTED", message="NetSuite connection not configured.", mode=self.mode)

    def sync_purchase_order(self, po_data: Dict[str, Any]) -> NetSuiteSyncResponse:
        """
        Synchronizes a ProcuraIQ Purchase Order to a NetSuite Purchase Order.
        """
        if self.client is None:
            return NetSuiteSyncResponse(
                success=False,
                error_message="Cannot sync Purchase Order: NetSuite connection not configured."
            )
            
        try:
            # Execute mapping
            mapped_data = self._map_purchase_order(po_data)
            
            # Send to NetSuite
            response = self.client.send_record("purchaseOrder", mapped_data)
            return NetSuiteSyncResponse(
                success=True,
                netsuite_id=response.get("internal_id"),
                raw_response=response
            )
        except Exception as e:
            return NetSuiteSyncResponse(
                success=False,
                error_message=str(e)
            )

    def _map_purchase_order(self, po_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Maps a ProcuraIQ PO dictionary to a NetSuite-compatible structure.
        Uses standard NetSuite field names where applicable.
        """
        return {
            "entity": {"id": po_data.get("vendor_id")}, # Maps to NetSuite Vendor
            "memo": "Generated by ProcuraIQ Automation",
            "item": {
                "items": [
                    {
                        "item": {"id": po_data.get("item_id", "DEFAULT_ITEM")},
                        "quantity": po_data.get("quantity", 1),
                        "rate": po_data.get("unit_price", 0.0)
                    }
                ]
            }
        }

# Global singleton adapter for the application lifecycle
netsuite_adapter = NetSuiteAdapter()
